/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleMars;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        AplicationManager manager = new AplicationManager(new Scanner(System.in));
        manager.launchExploration();
    }
}
